"""Application configuration and filesystem paths.

Everything the app writes at runtime (database, generated PDF reports, logs)
lives under the per-user application data directory so that SiteScope works
correctly when installed to C:\\Program Files, which is read-only for
standard Windows users.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

APP_NAME = "SiteScope"


def is_frozen() -> bool:
    """True when running from a PyInstaller-built executable."""
    return getattr(sys, "frozen", False)


def resource_dir() -> Path:
    """Directory containing bundled read-only resources (templates, static)."""
    if is_frozen():
        # PyInstaller unpacks bundled data into a temp dir exposed as _MEIPASS.
        # The default keeps this working if a future bootloader drops it.
        return Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
    return Path(__file__).resolve().parent


def data_dir() -> Path:
    """Writable per-user data directory.

    Windows: %LOCALAPPDATA%\\SiteScope
    macOS:   ~/Library/Application Support/SiteScope
    Linux:   ~/.local/share/SiteScope
    """
    override = os.environ.get("SITESCOPE_DATA_DIR")
    if override:
        path = Path(override)
    elif sys.platform == "win32":
        base = os.environ.get("LOCALAPPDATA") or os.path.expanduser("~")
        path = Path(base) / APP_NAME
    elif sys.platform == "darwin":
        path = Path.home() / "Library" / "Application Support" / APP_NAME
    else:
        base = os.environ.get("XDG_DATA_HOME") or os.path.join(os.path.expanduser("~"), ".local", "share")
        path = Path(base) / APP_NAME

    path.mkdir(parents=True, exist_ok=True)
    return path


def db_path() -> Path:
    return data_dir() / "sitescope.db"


def reports_dir() -> Path:
    path = data_dir() / "reports"
    path.mkdir(parents=True, exist_ok=True)
    return path


def settings_path() -> Path:
    return data_dir() / "settings.json"


# --------------------------------------------------------------------------
# User-adjustable settings
# --------------------------------------------------------------------------

DEFAULT_SETTINGS: dict = {
    # Crawling
    "max_pages": 25,             # pages fetched during a Full Scan
    "request_timeout": 12,       # seconds per HTTP request
    "requests_per_second": 5.0,  # politeness rate limit
    "respect_robots": True,      # honour robots.txt Disallow rules
    "follow_redirects": True,
    "verify_tls_errors": True,   # report certificate problems rather than ignoring them
    "user_agent": f"SiteScope/{APP_NAME} security scanner (authorised assessment)",
    # Reporting
    "business_name": "",
    "report_footer": "Generated by SiteScope",
    # Behaviour
    "demo_data_loaded": True,
}


def load_settings() -> dict:
    settings = dict(DEFAULT_SETTINGS)
    path = settings_path()
    if path.exists():
        try:
            stored = json.loads(path.read_text(encoding="utf-8"))
            if isinstance(stored, dict):
                settings.update({k: v for k, v in stored.items() if k in DEFAULT_SETTINGS})
        except (ValueError, OSError):
            pass
    return settings


def save_settings(values: dict) -> dict:
    settings = load_settings()
    for key, value in values.items():
        if key in DEFAULT_SETTINGS:
            settings[key] = value
    settings_path().write_text(json.dumps(settings, indent=2), encoding="utf-8")
    return settings
